### ISSUE TITLE
ERROR in ./node_modules/babel-loader/lib!./node_modules/vue-loader/lib/selector.js?type=script&index=0!./src/js/components/Hello.vue

### ISSUE THREAD

**Issue by CodyDeeds** [wpuricz/ipfs-eos-demo#1]
ERROR in ./node_modules/babel-loader/lib!./node_modules/vue-loader/lib/selector.js?type=script&index=0!./src/js/components/Hello.vue
Module not found: Error: Can't resolve '../../../config/secrets' in '/home/user/ipfs-eos-demo/src/js/components'
 @ ./node_modules/babel-loader/lib!./node_modules/vue-loader/lib/selector.js?type=script&index=0!./src/js/components/Hello.vue 32:0-46
 @ ./src/js/components/Hello.vue
 @ ./src/js/router/index.js
 @ ./src/js/main.js
 @ multi (webpack)-dev-server/client?http://localhost:8080 webpack/hot/dev-server ./src/js/main.js

**Comment by CodyDeeds** [comment]
getting this error when running

**Comment by wpuricz** [comment]
Create a file called secrets.js and put it in the config directory. Add your endpoint and keys needed. I forgot to put this in the readme. I will update the readme when I get a chance. The file looks like this:

module.exports = {

    endpoint: "http://x.x.x.x:8888",
    keys: [
        'keygoeshere,
        'keygoeshere',
    ]
  };

**Comment by wpuricz** [comment]
Added config file instructions to the README

**Comment by afreeneee** [comment]
did u get solution for your posted query

**Comment by sparcusa** [comment]
Hi Will,

 In secrets.js,   what keys are you looking for here?   EOS public keys or IPFS?  I'm new to both so sorry if this is a stupid question.   

I'm interested in this pattern.   Thanks for putting this out there.

**Comment by wpuricz** [comment]
It’s looking for the EOS private key to sign transactions. In practice you would never do this. You would integrate with scatter to sign the transaction. But this is just a demo. My other repository shows scatter integration (but the code may be outdated)
